# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9073ef51dc3ce83b130b3255d0b2fb48698c78942e572c2c231ef2d7fbef911d7e82cae8f67f5e888b14f5fce2074e45c28437ad42c8b37787c68367e02b00d

test:
  secret_key_base: 24af60642506aa9b712d2d170d3a601effeeeaeec3545aa79eaf594a499cb734c1b44b986047e8758e55bf7109c055f408b4985977366f16db4cc1d5fc196846

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
